// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityf2;

#nullable disable

namespace entityf2.Migrations
{
    [DbContext(typeof(StudentDb))]
    [Migration("20260424095000_v1.3")]
    partial class v13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("entityf2.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Studentid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Studentid");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "C#"
                        });
                });

            modelBuilder.Entity("entityf2.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CourseId = 1,
                            age = 20,
                            name = "Tony"
                        });
                });

            modelBuilder.Entity("entityf2.Course", b =>
                {
                    b.HasOne("entityf2.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("Studentid");
                });

            modelBuilder.Entity("entityf2.Student", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
