// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entityf2;

#nullable disable

namespace entityf2.Migrations
{
    [DbContext(typeof(StudentDb))]
    partial class StudentDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("Coursesid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Studentsid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Coursesid", "Studentsid");

                    b.HasIndex("Studentsid");

                    b.ToTable("CourseStudent");

                    b.HasData(
                        new
                        {
                            Coursesid = 1,
                            Studentsid = 1
                        });
                });

            modelBuilder.Entity("entityf2.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "C#"
                        });
                });

            modelBuilder.Entity("entityf2.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 20,
                            name = "Tony"
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("entityf2.Course", null)
                        .WithMany()
                        .HasForeignKey("Coursesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entityf2.Student", null)
                        .WithMany()
                        .HasForeignKey("Studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
